# Generated by Django 4.1.7 on 2023-04-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('reproducciones', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
